#!/usr/bin/env python3
"""Generate `docs/audit-2026-09/slider-atlas.md` from the run's verdict files.

WHY THIS IS A SCRIPT AND NOT A DOCUMENT SOMEBODY WRITES.

The previous audit produced `slider-ground-truth.md` by hand, and its header spent three
revisions disagreeing with its own body about how many findings it contained — 49
headings, 47 distinct findings, 43 still open, and every one of those numbers was written
in a different week. A document generated from the data cannot drift from the data. Run
this twice and diff: the bytes are identical.

    python3 scripts/gen-slider-atlas.py --verdicts <dir> [--out docs/audit-2026-09]

Input is one `VERDICT` JSON per control, as the third stage of the atlas run writes them
(schema in the run's generator). Output is the markdown atlas and the JSON it was built
from, committed side by side so a reader can check any sentence against its source.

Modelled on `docs/audit-2026-09/briefs/gen-w2.py`, which generates the W2 briefs from one
table for the same reason it gives in its own header: "so a relaunch after a container
reset uses byte-identical prompts".
"""
import argparse, json, os, sys, collections

FAMILY_TITLE = {
    "tone": "Tone — Basic, Zones, Curve and the histogram drags",
    "colour": "Colour — the mixer, point colour and black & white",
    "look": "Look — grading, colour balance, film lab, primaries, printer lights",
    "detail": "Detail — sharpening, denoise and presence",
    "effects": "Effects — vignette and grain",
    "mask": "Masks — the adjustments, the selection rows and the tools",
    "export": "Export — the sliders that write a file, not a render",
    "geometry": "Geometry — crop",
}
FAMILY_ORDER = ["tone", "colour", "detail", "effects", "look", "mask", "export",
                "geometry"]
OVERALL_MARK = {"clean": "clean", "smallProblems": "small", "bigProblems": "**BIG**",
                "dispositioned": "dispositioned"}


def load(directory):
    out = []
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".json"):
            continue
        with open(os.path.join(directory, name)) as handle:
            try:
                out.append(json.load(handle))
            except json.JSONDecodeError as bad:
                print(f"skipping {name}: {bad}", file=sys.stderr)
    return out


def confirmed(verdict):
    return [p for p in verdict.get("problems", [])
            if p.get("verdict") in ("CONFIRMED", "PLAUSIBLE_NEEDS_MAC")]


def cite(row):
    line = row.get("line")
    return f"`{row.get('file', '?')}" + (f":{line}`" if line else "`")


def render(verdicts, worklist):
    families = collections.defaultdict(list)
    by_id = {}
    for v in verdicts:
        item = worklist.get(v["id"], {})
        by_id[v["id"]] = v
        families[item.get("family", "unsorted")].append((item, v))
    for group in families.values():
        group.sort(key=lambda pair: pair[1]["id"])

    big = [(i, v, p) for group in families.values() for (i, v) in group
           for p in confirmed(v) if p.get("big")]
    small = sum(1 for group in families.values() for (_, v) in group
                for p in confirmed(v) if not p.get("big"))
    rejected = sum(1 for group in families.values() for (_, v) in group
                   for p in v.get("problems", []) if p.get("verdict") == "REJECTED")
    corrections = sum(len(v.get("entryCorrections", [])) for v in verdicts)
    needs_mac = [(v["id"], m) for v in verdicts for m in v.get("needsMac", [])]

    L = []
    w = L.append
    w("# The slider atlas")
    w("")
    w("One entry per control a hand can drag: what it does, where it lives, the maths, "
      "and what happened when it was measured. Every entry was written by one agent, "
      "measured by a second and attacked by a third; what is printed below is the third "
      "one's corrected version, never the draft.")
    w("")
    w("**Generated by `scripts/gen-slider-atlas.py` from `slider-atlas.json`. Do not "
      "edit this file — edit the data or the generator.**")
    w("")
    def plural(n, one, many):
        return f"{n} {one if n == 1 else many}"

    w(f"- **{plural(len(verdicts), 'control', 'controls')}** with a verdict")
    w(f"- **{plural(len(big), 'big problem', 'big problems')}** — S1, or S2 met on an "
      "ordinary edit")
    w(f"- {plural(small, 'smaller confirmed problem', 'smaller confirmed problems')}")
    w(f"- {plural(rejected, 'claim', 'claims')} rejected by the refute pass")
    w(f"- {plural(corrections, 'correction', 'corrections')} the refute pass made to an "
      "entry")
    w(f"- {plural(len(needs_mac), 'question', 'questions')} this box could not settle, "
      "for the macOS lanes")
    w("")

    if big:
        w("## The big problems")
        w("")
        w("Ranked S1 first, then S2 by family. *What the photographer sees* is the "
          "refute pass's own sentence.")
        w("")
        for item, v, p in sorted(big, key=lambda t: (t[2].get("severity", "S3"), t[1]["id"])):
            w(f"### {v['id']} — {p['title']} — {p.get('severity', '?')}")
            w("")
            w(f"**What the photographer sees.** {p.get('whatThePhotographerSees', '—')}")
            w("")
            if p.get("ordinaryEdit"):
                w(f"**The ordinary edit that meets it.** {p['ordinaryEdit']}")
                w("")
            w(f"**Verdict.** {p.get('verdict')} — {p.get('reason', '')}")
            w("")
            if p.get("measuredByAdversary"):
                w(f"**Reproduced.** {p['measuredByAdversary']}")
                w("")
        w("")

    w("## Every control")
    w("")
    w("| control | panel | verdict | big | small | records |")
    w("|---|---|---|---|---|---|")
    for family in FAMILY_ORDER + [f for f in sorted(families) if f not in FAMILY_ORDER]:
        for item, v in families.get(family, []):
            problems = confirmed(v)
            entry = v.get("entry", {})
            w(f"| `{v['id']}` | {entry.get('panel') or item.get('panel', '')} "
              f"| {OVERALL_MARK.get(v.get('overall'), v.get('overall', '?'))} "
              f"| {sum(1 for p in problems if p.get('big'))} "
              f"| {sum(1 for p in problems if not p.get('big'))} "
              f"| {'yes' if (item.get('spec') or {}).get('hasCommittedRecord') else '—'} |")
    w("")

    for family in FAMILY_ORDER + [f for f in sorted(families) if f not in FAMILY_ORDER]:
        group = families.get(family)
        if not group:
            continue
        w(f"## {FAMILY_TITLE.get(family, family)}")
        w("")
        for item, v in group:
            entry = v.get("entry", {})
            problems = confirmed(v)
            mark = OVERALL_MARK.get(v.get("overall"), "")
            w(f"### `{v['id']}` — {entry.get('displayName', item.get('displayName', ''))}"
              f"{' — ' + mark if mark not in ('clean', '') else ''}")
            w("")
            w(entry.get("whatItDoes", "—"))
            w("")
            rng = entry.get("range") or {}
            if rng:
                w(f"**Range.** {rng.get('soft', '?')} soft, "
                  f"{rng.get('hard') or 'no wider hard range'}, step {rng.get('step', '?')}, "
                  f"{rng.get('scale', 'linear')} axis, default {rng.get('default', '?')}"
                  f"{' (the identity)' if rng.get('defaultIsIdentity') else ' — NOT the identity'}.")
                w("")
            for m in entry.get("math", []):
                w(f"**Maths.** `{m['formula']}` — {cite(m)}"
                  + (f". {m['note']}" if m.get("note") else "."))
                if m.get("constants"):
                    w("")
                    w("Constants: " + ", ".join(f"`{c}`" for c in m["constants"]) + ".")
                w("")
            help_check = entry.get("helpAgreesWithEngine") or {}
            if help_check and not help_check.get("agrees", True):
                w(f"**The help text and the engine disagree.** {help_check.get('note', '')}")
                w("")
            for d in entry.get("specCodeDisagreements", []):
                w(f"**Spec against code.** {d.get('what', '')} — {cite(d)}, "
                  f"quoting: *{d.get('quote', '')}*")
                w("")
            for p in problems:
                w(f"**{p.get('severity', '?')}"
                  f"{' · BIG' if p.get('big') else ''} — {p['title']}.** "
                  f"{p.get('whatThePhotographerSees', '')} "
                  f"({p.get('verdict')}: {p.get('reason', '')})")
                w("")
            if not problems:
                w("Nothing survived the refute pass.")
                w("")
            corrected = v.get("entryCorrections", [])
            if corrected:
                w("<details><summary>Corrected by the refute pass</summary>")
                w("")
                for c in corrected:
                    w(f"- `{c['field']}`: was *{c['was']}*, now *{c['now']}* — {c['why']}")
                w("")
                w("</details>")
                w("")
    if needs_mac:
        w("## For the macOS lanes")
        w("")
        w("| control | question | lane |")
        w("|---|---|---|")
        for control, m in sorted(needs_mac):
            w(f"| `{control}` | {m.get('what', '')} | {m.get('lane', '')} |")
        w("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verdicts", required=True)
    ap.add_argument("--worklist", default=None)
    ap.add_argument("--out", default="docs/audit-2026-09")
    a = ap.parse_args()
    verdicts = load(a.verdicts)
    if not verdicts:
        sys.exit(f"no verdict files in {a.verdicts}")
    worklist = {}
    if a.worklist and os.path.exists(a.worklist):
        with open(a.worklist) as handle:
            worklist = {i["id"]: i for i in json.load(handle)["items"]}
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(a.out, "slider-atlas.md"), "w") as handle:
        handle.write(render(verdicts, worklist))
    with open(os.path.join(a.out, "slider-atlas.json"), "w") as handle:
        json.dump(sorted(verdicts, key=lambda v: v["id"]), handle, indent=1,
                  sort_keys=True)
        handle.write("\n")
    print(f"{len(verdicts)} verdicts -> {a.out}/slider-atlas.md")


if __name__ == "__main__":
    main()
