// Fingerprint.swift
// Recipe and blob fingerprints: XXH64 (Yann Collet's xxHash, 64-bit variant), seed 0.
//
// docs/15 names xxh3 for `recipe_fp`; tonight's implementation ships the simpler,
// equally deterministic XXH64 and records the deviation in BUILDING.md — the format
// prefix ("xxh64:") makes any future algorithm change self-describing. Fingerprints
// are cache keys, not security: collision resistance at 64 bits is ample for one
// photographer's catalog.
//
// Verified against Python's `xxhash` package via Tests/LumenCoreTests/Fixtures/
// fingerprint.json (generated by scripts/gen-fixtures.py).

import Foundation

public enum XXH64 {
    private static let prime1: UInt64 = 0x9E3779B185EBCA87
    private static let prime2: UInt64 = 0xC2B2AE3D27D4EB4F
    private static let prime3: UInt64 = 0x165667B19E3779F9
    private static let prime4: UInt64 = 0x85EBCA77C2B2AE63
    private static let prime5: UInt64 = 0x27D4EB2F165667C5

    public static func hash(_ data: [UInt8], seed: UInt64 = 0) -> UInt64 {
        let len = data.count
        var h: UInt64
        var index = 0

        if len >= 32 {
            var v1 = seed &+ prime1 &+ prime2
            var v2 = seed &+ prime2
            var v3 = seed
            var v4 = seed &- prime1
            let limit = len - 32
            while index <= limit {
                v1 = round(v1, read64(data, index)); index += 8
                v2 = round(v2, read64(data, index)); index += 8
                v3 = round(v3, read64(data, index)); index += 8
                v4 = round(v4, read64(data, index)); index += 8
            }
            h = rotl(v1, 1) &+ rotl(v2, 7) &+ rotl(v3, 12) &+ rotl(v4, 18)
            h = mergeRound(h, v1)
            h = mergeRound(h, v2)
            h = mergeRound(h, v3)
            h = mergeRound(h, v4)
        } else {
            h = seed &+ prime5
        }

        h &+= UInt64(len)

        while index + 8 <= len {
            let k = round(0, read64(data, index))
            h ^= k
            h = rotl(h, 27) &* prime1 &+ prime4
            index += 8
        }
        if index + 4 <= len {
            h ^= UInt64(read32(data, index)) &* prime1
            h = rotl(h, 23) &* prime2 &+ prime3
            index += 4
        }
        while index < len {
            h ^= UInt64(data[index]) &* prime5
            h = rotl(h, 11) &* prime1
            index += 1
        }

        h ^= h >> 33
        h &*= prime2
        h ^= h >> 29
        h &*= prime3
        h ^= h >> 32
        return h
    }

    public static func hash(_ string: String, seed: UInt64 = 0) -> UInt64 {
        hash(Array(string.utf8), seed: seed)
    }

    /// Lowercase 16-digit hex, zero-padded — the wire form used in "xxh64:<hex>" refs.
    public static func hexDigest(_ string: String, seed: UInt64 = 0) -> String {
        String(format: "%016llx", hash(string, seed: seed))
    }

    // MARK: - internals

    private static func rotl(_ x: UInt64, _ r: UInt64) -> UInt64 {
        (x << r) | (x >> (64 - r))
    }

    private static func round(_ acc: UInt64, _ input: UInt64) -> UInt64 {
        var acc = acc &+ input &* prime2
        acc = rotl(acc, 31)
        return acc &* prime1
    }

    private static func mergeRound(_ acc: UInt64, _ val: UInt64) -> UInt64 {
        let v = round(0, val)
        var acc = acc ^ v
        return acc &* prime1 &+ prime4
    }

    private static func read64(_ d: [UInt8], _ i: Int) -> UInt64 {
        var v: UInt64 = 0
        for b in 0..<8 { v |= UInt64(d[i + b]) << (8 * UInt64(b)) }  // little-endian
        return v
    }

    private static func read32(_ d: [UInt8], _ i: Int) -> UInt32 {
        var v: UInt32 = 0
        for b in 0..<4 { v |= UInt32(d[i + b]) << (8 * UInt32(b)) }
        return v
    }
}

public enum RecipeFingerprint {
    /// The catalog's `recipe_fp`: xxh64 of the canonical sparse JSON.
    public static func fingerprint(_ recipe: Recipe) throws -> String {
        "xxh64:" + XXH64.hexDigest(try CanonicalJSON.canonicalRecipeJSON(recipe))
    }

    /// Fingerprint of the parameter subset that changes AI-denoise input pixels
    /// (docs/07: WB and decoder identity materially change the denoiser's input;
    /// downstream look parameters must NOT invalidate the cached artifact).
    public static func denoiseInputFingerprint(_ recipe: Recipe) -> String {
        let r = recipe.develop.raw
        var s = "v1|decoder=\(r.decoder)|dv=\(r.decoderVersion.map(String.init) ?? "-")"
        s += "|temp=\(r.temp.map(CanonicalJSON.canonicalNumber) ?? "asShot")"
        s += "|tint=\(r.tint.map(CanonicalJSON.canonicalNumber) ?? "asShot")"
        s += "|model=\(recipe.develop.denoise.model ?? "default")"
        return "xxh64:" + XXH64.hexDigest(s)
    }
}
